### ISSUE TITLE
Avoid the need to include mutest in the bundle

### ISSUE THREAD

**Issue by mvz** [backus/mutest#33]
For casual introduction of mutest into a project, it would be nice if you could just run

```bash
mutest --use rspec --jobs 4 'Some::Class'
```

without having to add `mutest-rspec` to the bundle first.

**Comment by backus** [comment]
You can also just depend on `mutest-rspec` and that will pull in `mutest` as well. What do you think about that?

**Comment by mvz** [comment]
That's what I'm doing. I mean not having to add mutant or mutant-spec to the bundle at all.

**Comment by backus** [comment]
Yeah what I meant was that you can include *only* `mutest-rspec` in your bundle and it will pull in `mutest`. Are you saying we should just add `mutest-rspec` as a dependency to `mutest`? That seems reasonable since there aren't other implementations.

**Comment by mvz** [comment]
It seems we're misunderstanding each other. I'm talking about not adding anything to the bundle and running `mutest` on a project that doesn't know anything about mutest yet. So it would let me check out a random project and just immediately run mutest on it, similarly to how you can rubocop or reek on a project that doesn't know anything about those tools.

This is definitely a wishlist-level issue, by the way!

**Comment by backus** [comment]
Ah I get what you mean. I agree that would be nice. Maybe we should just kill the separate gem

**Comment by mvz** [comment]
I'm wondering why it is not found when mutest is run without bundle exec. Something strange is going on there.

**Comment by backus** [comment]
`mutest` excludes the integrations from the source files it ships: https://github.com/backus/mutest/blob/master/mutest.gemspec#L16

**Comment by mvz** [comment]
The code that loads the integration calls `require` on the passed-in `kernel` object. Usually, this is `Kernel`. However, it seems `Kernel.require` is not identical to the regular `require`: In that context at least, when running outside of `bundle exec`, calling `require 'mutest/integration/rspec'` works, but `Kernel.require 'mutest/integration/rspec'` does not work.

**Comment by mvz** [comment]
I've created a quick-and-dirty fix in #41.
